### ISSUE TITLE
1.14.4 server issue 

### ISSUE THREAD

**Issue by Shadow3641** [skyjay1/Nomadic-Tents#27]
While trying to create a server with only this mod installed I get the following crash

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/21/19 2:11 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Can not register a null dimension type
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[server-1.14.4-extra.jar:?] {}
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:102) ~[?:?] {}
	at nomadictents.dimension.TentManager.registerDimension(TentManager.java:22) ~[?:10.0.1-beta] {}
	at nomadictents.event.TentEventHandler.onServerStarting(TentEventHandler.java:35) ~[?:10.0.1-beta] {}
	at net.minecraftforge.eventbus.ASMEventHandler_8_TentEventHandler_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:76) ~[?:?] {}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:241) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 5.0.0-27-generic
	Java Version: 1.8.0_222, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 2880489536 bytes (2747 MB) / 3474456576 bytes (3313 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms1024M -Xmx8192M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		NomadicTents-1.14.4-10.0.1-beta.jar Nomadic Tents {nomadictents@10.0.0-beta CONSTRUCT}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 DONE}
		forge-1.14.4-28.1.0-server.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:nomadictents, mod:forge
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

[crash-2019-09-21_14.11.02-server.txt](https://github.com/skyjay1/Nomadic-Tents/files/3639004/crash-2019-09-21_14.11.02-server.txt)

**Comment by skyjay1** [comment]
Unable to replicate crash, but just in case I did some things like pre-initializing the config and null-checks. Let me know if it happens again using release 10.0.2
