### ISSUE TITLE
[1.14.4] Sidedness issue when run on a dedicated server- Attempted to load class net/minecraft/client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by ProsperCraft** [skyjay1/Nomadic-Tents#29]
```
[15:08:35] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[15:08:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Nomadic Tents (nomadictents) has failed to load correctly
§7Attempted to load class net/minecraft/client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:198) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:180) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
[15:08:35] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /opt/adventuresofhalk/./crash-reports/crash-2019-10-05_15.08.35-server.txt
[15:08:35] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[15:08:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[15:08:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:978) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:521) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:544) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:661) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
```

Crash report - https://gist.github.com/ProsperCraft/66059c45a0c45053c606d5d23ac8cc4a

Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by skyjay1** [comment]
See #19

**Comment by ProsperCraft** [comment]
This happens without midnight-
https://paste.fedoraproject.org/paste/QyK5rcPyTaW0zccmX2ajxA

**Comment by ProsperCraft** [comment]
Looking for a build with that fix please :)

**Comment by Nachtflame** [comment]
Also experiencing the issue. Also, no Midnight installed.

**Comment by ProsperCraft** [comment]
He made a fix but didn't push a new build to curse, not sure why.

**Comment by skyjay1** [comment]
Still working on fixing this one, it keeps crashing when I try testing on a server so it might be a bit. Thank you for your patience.

**Comment by Nachtflame** [comment]
Thanks for the update! Be glad when this is fixed, as it's holding up my ability to spin-up a test server for my pack. 😄

**Comment by Nachtflame** [comment]
Any news? How about a config like the older versions, where we can disable each type of tent?

~My apologies, but I'm at a point in developing my pack where I need to make a decision on what to do with your mod.  If there is a viable fix being worked on, then I await it eagerly.  But if you're having problems figuring it out, then I'll have to figure out something else.

Thank you.

**Comment by Sarioah** [comment]
FWIW I tried compiling 10.0.2-beta and it still doesn't work; crashes with the same error...

Would be great to see this working, but unfortunately I've had to pull it from my personal little pack for now :|

EDIT: this mod had the same issue, might be worth digging through their code if it's available and see what they did to fix it...
https://github.com/RobertSkalko/Mine-and-Slash/issues/84

**Comment by Sarioah** [comment]
Might be this commit that fixed it for them??
https://github.com/RobertSkalko/Mine-and-Slash/commit/f93ffc41847b31337e76721f88b460fdeae97896

**Comment by Nachtflame** [comment]
New update [NomadicTents-1.14.4-10.0.2-beta] appears to have successfully fixed the issue!

Thank you!! :D

**Comment by skyjay1** [comment]
> Might be this commit that fixed it for them??
> [RobertSkalko/Mine-and-Slash@f93ffc4](https://github.com/RobertSkalko/Mine-and-Slash/commit/f93ffc41847b31337e76721f88b460fdeae97896)

Thank you for finding that, examining RobertSkalko's code helped me to identify the problem. Please stress-test the newest release as much as possible so I can keep fixing things :)
