### ISSUE TITLE
Can't enter tent

### ISSUE THREAD

**Issue by Banana99999** [skyjay1/Nomadic-Tents#79]
https://github.com/skyjay1/Nomadic-Tents/assets/119025712/2e1572b8-2a10-4012-925b-db3f43e05650

**Comment by Techognito** [comment]
I see the same issue with: 
Nomadic Tents version: 19.2.0
Forge Version: 43.3.2
MC version: 1.19.2


<details><summary>ErrorLog</summary>
<p>

```
[11:53:48] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@ec20b29, suppressing error
java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:dimension / nomadictents:67d0305d-510e-40de-a9d4-c1e4062abe53])
	at net.minecraft.core.MappedRegistry.m_205921_(MappedRegistry.java:78) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_205857_(MappedRegistry.java:96) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_203704_(MappedRegistry.java:83) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_203505_(MappedRegistry.java:138) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at nomadictents.dimension.DynamicDimensionHelper.createAndRegisterWorldAndDimension(DynamicDimensionHelper.java:195) ~[nomadictents-19.2.0.jar%23152!/:19.2.0] {re:classloading}
	at nomadictents.dimension.DynamicDimensionHelper.getOrCreateWorld(DynamicDimensionHelper.java:161) ~[nomadictents-19.2.0.jar%23152!/:19.2.0] {re:classloading}
	at nomadictents.tileentity.TentDoorBlockEntity.onEnter(TentDoorBlockEntity.java:319) ~[nomadictents-19.2.0.jar%23152!/:19.2.0] {re:classloading}
	at nomadictents.tileentity.TentDoorBlockEntity.use(TentDoorBlockEntity.java:110) ~[nomadictents-19.2.0.jar%23152!/:19.2.0] {re:classloading}
	at nomadictents.block.TentDoorBlock.m_6227_(TentDoorBlock.java:118) ~[nomadictents-19.2.0.jar%23152!/:19.2.0] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:714) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:340) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

</p>
</details>

**Comment by Techognito** [comment]
I saw in gradle.properties that it used forge 43.1.7

The same issue is in that version as well:
<details><summary>ErrorLog</summary>
<p>

```
[12:14:39] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@5aae9d1a, suppressing error
java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:dimension / nomadictents:3081d214-853f-4b6b-a389-66757501a4a1])
	at net.minecraft.core.MappedRegistry.m_205921_(MappedRegistry.java:78) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_205857_(MappedRegistry.java:96) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_203704_(MappedRegistry.java:83) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_203505_(MappedRegistry.java:138) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at nomadictents.dimension.DynamicDimensionHelper.createAndRegisterWorldAndDimension(DynamicDimensionHelper.java:195) ~[nomadictents-19.2.0.jar%23136!/:19.2.0] {re:classloading}
	at nomadictents.dimension.DynamicDimensionHelper.getOrCreateWorld(DynamicDimensionHelper.java:161) ~[nomadictents-19.2.0.jar%23136!/:19.2.0] {re:classloading}
	at nomadictents.tileentity.TentDoorBlockEntity.onEnter(TentDoorBlockEntity.java:319) ~[nomadictents-19.2.0.jar%23136!/:19.2.0] {re:classloading}
	at nomadictents.tileentity.TentDoorBlockEntity.use(TentDoorBlockEntity.java:110) ~[nomadictents-19.2.0.jar%23136!/:19.2.0] {re:classloading}
	at nomadictents.block.TentDoorBlock.m_6227_(TentDoorBlock.java:118) ~[nomadictents-19.2.0.jar%23136!/:19.2.0] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:714) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:340) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23139!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
``` 

</p>
</details>

**Comment by Techognito** [comment]
Not sure what I did to make it work, I believe it's because I was messing around with JEI versions. I added JEI 11.2.0.256, but I didn't enable it. After that it worked fine with JEI 11.6.0.1018

And so far testing FORGE 43.1.10 & 43.1.12 have been successful

**Comment by KiriCattus** [comment]
Bit late to this but I didn't deal with the mod back then, testing this now doing the same as the video did using Forge 43.5.0 and Nomadic Tents 19.2.0 I can't seem to be able to reproduce the issue, I assume something changed with either older versions of Forge or JEI (I suspect Forge with the error log snippet provided) that resolved the issue, that said I think this can be closed off now both beause of that and the age of it :)
